export const GET_COUNTRIES_FAIL = "GET_COUNTRIES_FAIL";
export const GET_COUNTRIES_SUCCESS = "GET_COUNTRIES_SUCCESS";
export const GET_COUNTRIES_LOAD = "GET_COUNTRIES_LOAD";
export const GET_COUNTRY = "GET_COUNTRY";
