export const GET_RESERVATIONS_FAIL = "GET_RESERVATIONS_FAIL";
export const GET_RESERVATIONS_SUCCESS = "GET_RESERVATIONS_SUCCESS";
export const GET_RESERVATIONS_LOAD = "GET_RESERVATIONS_LOAD";
export const GET_RESERVATION = "GET_RESERVATION";
export const GET_RESERVATIONS_SUCCESS_BY_HOTEL = "GET_RESERVATIONS_SUCCESS_BY_HOTEL";
export const GET_RESERVATIONS_LOAD_By_HOTEL = "GET_RESERVATIONS_LOAD_By_HOTEL";
export const GET_RESERVATIONS_FAIL_BY_HOTEL = "GET_RESERVATIONS_FAIL_BY_HOTEL";
