export const GET_VOUCHERS_FAIL = "GET_VOUCHERS_FAIL";
export const GET_VOUCHERS_SUCCESS = "GET_VOUCHERS_SUCCESS";
export const GET_VOUCHERS_LOAD = "GET_VOUCHERS_LOAD";
export const GET_VOUCHER = "GET_VOUCHER";
export const GET_VOUCHERS_SUCCESS_BY_HOTEL = "GET_VOUCHERS_SUCCESS_BY_HOTEL";
export const GET_VOUCHERS_LOAD_By_HOTEL = "GET_VOUCHERS_LOAD_By_HOTEL";
export const GET_VOUCHERS_FAIL_BY_HOTEL = "GET_VOUCHERS_FAIL_BY_HOTEL";
