export const GET_VOUCHERS_FAIL = "GET_VOUCHERS_FAIL";
export const GET_VOUCHERS_SUCCESS = "GET_VOUCHERS_SUCCESS";
export const GET_VOUCHERS_LOAD = "GET_VOUCHERS_LOAD";
export const GET_VOUCHER = "GET_VOUCHER";
